# Generated by Django 5.2.6 on 2025-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_auto_20201113_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
