# Generated by Django 5.2.6 on 2025-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-published_date", "-created")},
        ),
        migrations.RemoveField(
            model_name="article",
            name="draft",
        ),
        migrations.AddField(
            model_name="article",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
